## Data Gathering

Import all of the Required Libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

#Scikit learn is the library we require every time while building a ML project
pip install scikit-learn in terminal

In [7]:
#Data Gathering
df=pd.read_csv('International_Education_Costs.csv')

## Data Exploration

In [6]:
df.head()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
0,USA,Cambridge,Harvard University,Computer Science,Master,2.0,55400,83.5,2200,160,1500,1.00
1,UK,London,Imperial College London,Data Science,Master,1.0,41200,75.8,1800,485,800,0.79
2,Canada,Toronto,University of Toronto,Business Analytics,Master,2.0,38500,72.5,1600,235,900,1.35
3,Australia,Melbourne,University of Melbourne,Engineering,Master,2.0,42000,71.2,1400,450,650,1.52
4,Germany,Munich,Technical University of Munich,Mechanical Engineering,Master,2.0,500,70.5,1100,75,550,0.92

In [8]:
df.tail()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
902,France,Strasbourg,University of Strasbourg,Data Analytics,Master,2.0,4000,70.2,1000,99,850,0.92
903,Malaysia,Nilai,USIM,Computer Science,Bachelor,3.0,6800,50.5,400,120,400,4.65
904,Saudi Arabia,Al-Ahsa,King Faisal University,Information Systems,Master,2.0,4200,64.2,600,200,800,3.75
905,USA,Seattle,University of Washington,Software Development,PhD,5.0,50000,77.8,2000,160,1500,1.00
906,UK,Nottingham,University of Nottingham,Data Engineering,Master,2.0,34000,61.2,800,485,800,0.79

In [11]:
#returns 5 random rows from the dataset
df.sample(5)

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
246,UK,Sheffield,University of Sheffield,Computer Science,Bachelor,3.0,29800,70.5,1200,490,800,0.79
577,Spain,Valencia,Universitat de València,Data Science,Master,2.0,3200,68.5,800,80,750,0.92
378,Australia,Gold Coast,Griffith University,Computer Science,PhD,4.0,28200,68.5,1400,450,650,1.52
854,Malaysia,Penang,USM,Information Systems,Bachelor,3.0,7500,52.1,450,120,400,4.65
682,Brazil,Salvador,UFBA,Data Science,Master,2.0,0,46.8,380,90,400,4.95

In [12]:
df.describe()

,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
count,907.000000,907.000000,907.000000,907.000000,907.000000,907.000000,907.000000
mean,2.836825,16705.016538,64.437486,969.206174,211.396913,700.077178,623.000695
std,0.945449,16582.385275,14.056333,517.154752,143.435740,320.374875,3801.746134
min,1.000000,0.000000,27.800000,150.000000,40.000000,200.000000,0.150000
25%,2.000000,2850.000000,56.300000,545.000000,100.000000,450.000000,0.920000
50%,3.000000,7500.000000,67.500000,900.000000,160.000000,650.000000,1.350000
75%,4.000000,31100.000000,72.200000,1300.000000,240.000000,800.000000,7.150000
max,5.000000,62000.000000,122.400000,2500.000000,490.000000,1500.000000,42150.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            907 non-null    object
 1   City               907 non-null    object
 2   University         907 non-null    object
 3   Program            907 non-null    object
 4   Level              907 non-null    object
 5   Duration_Years     907 non-null    float64
 6   Tuition_USD        907 non-null    int64
 7   Living_Cost_Index  907 non-null    float64
 8   Rent_USD           907 non-null    int64
 9   Visa_Fee_USD       907 non-null    int64
 10  Insurance_USD      907 non-null    int64
 11  Exchange_Rate      907 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 85.2+ KB

In [ ]:
#Number of rows and columns
df.shape

(907, 12)

In [17]:
#Total elements present inside the dataframe
df.size

10884

In [18]:
df.dtypes

Country               object
City                  object
University            object
Program               object
Level                 object
Duration_Years       float64
Tuition_USD            int64
Living_Cost_Index    float64
Rent_USD               int64
Visa_Fee_USD           int64
Insurance_USD          int64
Exchange_Rate        float64
dtype: object

In [19]:
df['Country'].value_counts()

Country
UK                93
Australia         86
USA               78
Canada            76
Germany           33
                  ..
Czech Republic     1
Hong Kong          1
Israel             1
Nigeria            1
Vietnam            1
Name: count, Length: 71, dtype: int64

In [22]:
df['Country'].unique()

array(['USA', 'UK', 'Canada', 'Australia', 'Germany', 'Japan',
       'Netherlands', 'Singapore', 'France', 'Switzerland', 'Sweden',
       'Denmark', 'China', 'South Korea', 'Ireland', 'New Zealand',
       'Austria', 'Belgium', 'Hong Kong', 'Portugal', 'Israel', 'Taiwan',
       'Czech Republic', 'India', 'Poland', 'Malaysia', 'Spain', 'Italy',
       'Finland', 'Norway', 'Brazil', 'Turkey', 'Russia', 'Mexico',
       'Greece', 'Thailand', 'UAE', 'South Africa', 'Egypt', 'Argentina',
       'Indonesia', 'Saudi Arabia', 'Nigeria', 'Vietnam', 'Hungary',
       'Iceland', 'Colombia', 'Romania', 'Luxembourg', 'Tunisia',
       'Cyprus', 'Croatia', 'Dominican Republic', 'Morocco', 'Peru',
       'Ecuador', 'Lebanon', 'Bahrain', 'Uruguay', 'Bulgaria', 'Ghana',
       'Algeria', 'Panama', 'Bangladesh', 'Kuwait', 'Ukraine', 'Slovenia',
       'Serbia', 'Iran', 'Uzbekistan', 'El Salvador'], dtype=object)

In [23]:
#Rows where country=india will hae true value rest will have false value, and to know those rows we apply boolean indexing
df[df['Country']=='India']

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
44,India,Bangalore,Indian Institute of Science,Computer Science,Master,2.0,2500,45.6,500,200,300,83.20
648,India,Bangalore,Indian Institute of Science,Data Science,PhD,4.0,2000,45.2,300,180,300,82.75
654,India,Mumbai,IIT Bombay,Computer Engineering,Master,2.0,1800,47.5,350,180,300,82.75
659,India,Delhi,IIT Delhi,Artificial Intelligence,PhD,4.0,1900,44.8,320,180,300,82.75
665,India,Chennai,IIT Madras,Software Engineering,Master,2.0,1700,42.4,280,180,300,82.75
671,India,Hyderabad,IIT Hyderabad,Data Analytics,PhD,4.0,1800,41.2,260,180,300,82.75
677,India,Pune,IIT Pune,Computer Science,Master,2.0,1600,40.5,250,180,300,82.75
683,India,Kanpur,IIT Kanpur,Artificial Intelligence,PhD,4.0,1900,39.8,240,180,300,82.75

In [24]:
df['City'].value_counts()

City
Singapore    18
Melbourne    11
Sydney       11
London       10
Canberra      8
             ..
Tabuk         1
Shah Alam     1
Makkah        1
Nilai         1
Al-Ahsa       1
Name: count, Length: 556, dtype: int64

In [26]:
df['Program'].value_counts()

Program
Computer Science           312
Data Science                82
Computer Engineering        71
Software Engineering        57
Artificial Intelligence     53
                          ...
Electronics                  1
Electronic Engineering       1
Digital Design               1
Digital Business             1
Data Systems                 1
Name: count, Length: 92, dtype: int64

In [27]:
df['Level'].value_counts()

Level
Master      451
Bachelor    297
PhD         159
Name: count, dtype: int64

In [28]:
df['Duration_Years'].min()

np.float64(1.0)

In [29]:
df['Duration_Years'].max()

np.float64(5.0)

In [30]:
df['Duration_Years'].mean()

np.float64(2.8368246968026463)

## Data Cleaning and Preprocessing

In [31]:
#To check if we are having any missing value in our dataframe or not
df.isnull()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
902,False,False,False,False,False,False,False,False,False,False,False,False
903,False,False,False,False,False,False,False,False,False,False,False,False
904,False,False,False,False,False,False,False,False,False,False,False,False
905,False,False,False,False,False,False,False,False,False,False,False,False
906,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#No Null Value in this dataframe
df.isnull().sum()

Country              0
City                 0
University           0
Program              0
Level                0
Duration_Years       0
Tuition_USD          0
Living_Cost_Index    0
Rent_USD             0
Visa_Fee_USD         0
Insurance_USD        0
Exchange_Rate        0
dtype: int64

In [33]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
902    False
903    False
904    False
905    False
906    False
Length: 907, dtype: bool

In [ ]:
#No duplicates in this dataframe
df.duplicated().sum()

np.int64(0)

In [35]:
df.dtypes

Country               object
City                  object
University            object
Program               object
Level                 object
Duration_Years       float64
Tuition_USD            int64
Living_Cost_Index    float64
Rent_USD               int64
Visa_Fee_USD           int64
Insurance_USD          int64
Exchange_Rate        float64
dtype: object

In [36]:
#Change the datatype of the given column
df['Duration_Years']=df['Duration_Years'].astype('float32')

In [38]:
df['Tuition_USD']=df['Tuition_USD'].astype('int32')

In [39]:
df['Rent_USD']=df['Rent_USD'].astype('int32')
df['Visa_Fee_USD']=df['Visa_Fee_USD'].astype('int32')
df['Insurance_USD']=df['Insurance_USD'].astype('int32')

In [40]:
df.dtypes

Country               object
City                  object
University            object
Program               object
Level                 object
Duration_Years       float32
Tuition_USD            int32
Living_Cost_Index    float64
Rent_USD               int32
Visa_Fee_USD           int32
Insurance_USD          int32
Exchange_Rate        float64
dtype: object

In [ ]:
#size of dataset reduced from 85 to 67kb
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            907 non-null    object
 1   City               907 non-null    object
 2   University         907 non-null    object
 3   Program            907 non-null    object
 4   Level              907 non-null    object
 5   Duration_Years     907 non-null    float32
 6   Tuition_USD        907 non-null    int32
 7   Living_Cost_Index  907 non-null    float64
 8   Rent_USD           907 non-null    int32
 9   Visa_Fee_USD       907 non-null    int32
 10  Insurance_USD      907 non-null    int32
 11  Exchange_Rate      907 non-null    float64
dtypes: float32(1), float64(2), int32(4), object(5)
memory usage: 67.4+ KB

## Exploratory Data Analysis (EDA)